In [167]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.utils import pad_sequences
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from tensorflow.keras.models import Sequential
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, SimpleRNN
from tensorflow.keras.preprocessing.text import Tokenizer
from sklearn.model_selection import train_test_split
import string
from textblob import TextBlob
import joblib


In [168]:
len(open('data/test.txt', 'r').readlines())

2000

In [169]:
len(open('data/train.txt', 'r').readlines())

16000

In [170]:
len(open('data/val.txt', 'r').readlines())

2000

In [171]:
test_data = open('data/test.txt', 'r').readlines()
test_data

['im feeling rather rotten so im not very ambitious right now;sadness\n',
 'im updating my blog because i feel shitty;sadness\n',
 'i never make her separate from me because i don t ever want her to feel like i m ashamed with her;sadness\n',
 'i left with my bouquet of red and yellow tulips under my arm feeling slightly more optimistic than when i arrived;joy\n',
 'i was feeling a little vain when i did this one;sadness\n',
 'i cant walk into a shop anywhere where i do not feel uncomfortable;fear\n',
 'i felt anger when at the end of a telephone call;anger\n',
 'i explain why i clung to a relationship with a boy who was in many ways immature and uncommitted despite the excitement i should have been feeling for getting accepted into the masters program at the university of virginia;joy\n',
 'i like to have the same breathless feeling as a reader eager to see what will happen next;joy\n',
 'i jest i feel grumpy tired and pre menstrual which i probably am but then again its only been a we

In [172]:
train_data = open('data/train.txt', 'r').readlines()
train_data

['i didnt feel humiliated;sadness\n',
 'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake;sadness\n',
 'im grabbing a minute to post i feel greedy wrong;anger\n',
 'i am ever feeling nostalgic about the fireplace i will know that it is still on the property;love\n',
 'i am feeling grouchy;anger\n',
 'ive been feeling a little burdened lately wasnt sure why that was;sadness\n',
 'ive been taking or milligrams or times recommended amount and ive fallen asleep a lot faster but i also feel like so funny;surprise\n',
 'i feel as confused about life as a teenager or as jaded as a year old man;fear\n',
 'i have been with petronas for years i feel that petronas has performed well and made a huge profit;joy\n',
 'i feel romantic too;love\n',
 'i feel like i have to make the suffering i m seeing mean something;sadness\n',
 'i do feel that running is a divine experience and that i can expect to have some type of spiritual encounter;joy\n'

In [173]:
val_data = open('data/val.txt', 'r').readlines()
val_data

['im feeling quite sad and sorry for myself but ill snap out of it soon;sadness\n',
 'i feel like i am still looking at a blank canvas blank pieces of paper;sadness\n',
 'i feel like a faithful servant;love\n',
 'i am just feeling cranky and blue;anger\n',
 'i can have for a treat or if i am feeling festive;joy\n',
 'i start to feel more appreciative of what god has done for me;joy\n',
 'i am feeling more confident that we will be able to take care of this baby;joy\n',
 'i feel incredibly lucky just to be able to talk to her;joy\n',
 'i feel less keen about the army every day;joy\n',
 'i feel dirty and ashamed for saying that;sadness\n',
 'i feel bitchy but not defeated yet;anger\n',
 'i was dribbling on mums coffee table looking out of the window and feeling very happy;joy\n',
 'i woke up often got up around am feeling pukey radiation and groggy;sadness\n',
 'i was feeling sentimental;sadness\n',
 'i walked out of there an hour and fifteen minutes later feeling like i had been beaten 

In [174]:
total_data = test_data + train_data + val_data

In [175]:
len(total_data)

20000

In [176]:
x = []
y = []

for item in total_data:
    text, label = item.split(';')
    label = label.replace('\n', '')
    x.append(text)
    y.append(label)


In [177]:
x

['im feeling rather rotten so im not very ambitious right now',
 'im updating my blog because i feel shitty',
 'i never make her separate from me because i don t ever want her to feel like i m ashamed with her',
 'i left with my bouquet of red and yellow tulips under my arm feeling slightly more optimistic than when i arrived',
 'i was feeling a little vain when i did this one',
 'i cant walk into a shop anywhere where i do not feel uncomfortable',
 'i felt anger when at the end of a telephone call',
 'i explain why i clung to a relationship with a boy who was in many ways immature and uncommitted despite the excitement i should have been feeling for getting accepted into the masters program at the university of virginia',
 'i like to have the same breathless feeling as a reader eager to see what will happen next',
 'i jest i feel grumpy tired and pre menstrual which i probably am but then again its only been a week and im about as fit as a walrus on vacation for the summer',
 'i don t

In [178]:
y

['sadness',
 'sadness',
 'sadness',
 'joy',
 'sadness',
 'fear',
 'anger',
 'joy',
 'joy',
 'anger',
 'fear',
 'sadness',
 'fear',
 'joy',
 'love',
 'sadness',
 'joy',
 'sadness',
 'anger',
 'joy',
 'sadness',
 'joy',
 'joy',
 'sadness',
 'sadness',
 'fear',
 'anger',
 'sadness',
 'fear',
 'anger',
 'fear',
 'anger',
 'sadness',
 'anger',
 'sadness',
 'joy',
 'joy',
 'sadness',
 'joy',
 'joy',
 'anger',
 'sadness',
 'joy',
 'sadness',
 'joy',
 'anger',
 'joy',
 'joy',
 'fear',
 'fear',
 'sadness',
 'fear',
 'joy',
 'sadness',
 'joy',
 'sadness',
 'sadness',
 'joy',
 'sadness',
 'anger',
 'sadness',
 'sadness',
 'joy',
 'joy',
 'sadness',
 'surprise',
 'sadness',
 'anger',
 'fear',
 'surprise',
 'joy',
 'love',
 'surprise',
 'joy',
 'love',
 'anger',
 'joy',
 'sadness',
 'joy',
 'love',
 'joy',
 'anger',
 'sadness',
 'joy',
 'sadness',
 'sadness',
 'joy',
 'joy',
 'joy',
 'sadness',
 'joy',
 'fear',
 'anger',
 'fear',
 'anger',
 'anger',
 'love',
 'sadness',
 'anger',
 'sadness',
 'sadn

#### Text Cleaning Steps


In [179]:
stem = PorterStemmer()

In [180]:
def text_cleaning(sentence):
    clean_text = []
    for sent in sentence:
        lower_sent = sent.lower()  # Lower case
        word_tokenized = word_tokenize(lower_sent)
        removed_stopwords = [word for word in word_tokenized if word not in stopwords.words('english')]   
        # remove stop words
        stemmed_sent = [stem.stem(word) for word in removed_stopwords]
        cleaned = " ".join(stemmed_sent)  # join
        clean_text.append(cleaned)
    return clean_text
        

In [181]:
clean_Data = text_cleaning(x)

In [182]:
clean_Data


['im feel rather rotten im ambiti right',
 'im updat blog feel shitti',
 'never make separ ever want feel like asham',
 'left bouquet red yellow tulip arm feel slightli optimist arriv',
 'feel littl vain one',
 'cant walk shop anywher feel uncomfort',
 'felt anger end telephon call',
 'explain clung relationship boy mani way immatur uncommit despit excit feel get accept master program univers virginia',
 'like breathless feel reader eager see happen next',
 'jest feel grumpi tire pre menstrual probabl week im fit walru vacat summer',
 'feel particularli agit',
 'feel beauti emot know women knew hand hold baba journey',
 'pay attent deepen feel invad helpless',
 'feel extrem comfort group peopl dont even need hide',
 'find odd posit feel support',
 'feel heartbroken im sure katniss',
 'feel littl mellow today',
 'feel like role would tear sail pessim discont',
 'feel bcoz fight get mad n u wan na make public n let world know fight',
 'feel like red purpl rich kind perfect',
 'im sure fe

In [183]:
tokenizer = Tokenizer(oov_token='<nothing>')

In [184]:
tokenizer.fit_on_texts(clean_Data)

In [185]:
tokenizer.word_index

{'<nothing>': 1,
 'feel': 2,
 'like': 3,
 'im': 4,
 'get': 5,
 'time': 6,
 'know': 7,
 'realli': 8,
 'make': 9,
 'go': 10,
 'want': 11,
 'love': 12,
 'littl': 13,
 'think': 14,
 'peopl': 15,
 'day': 16,
 'thing': 17,
 'one': 18,
 'would': 19,
 'even': 20,
 'still': 21,
 'ive': 22,
 'life': 23,
 'bit': 24,
 'way': 25,
 'need': 26,
 'someth': 27,
 'much': 28,
 'dont': 29,
 'work': 30,
 'start': 31,
 'could': 32,
 'say': 33,
 'look': 34,
 'see': 35,
 'tri': 36,
 'back': 37,
 'good': 38,
 'pretti': 39,
 'come': 40,
 'right': 41,
 'alway': 42,
 'help': 43,
 'also': 44,
 'today': 45,
 'year': 46,
 'take': 47,
 'friend': 48,
 'use': 49,
 'around': 50,
 'cant': 51,
 'person': 52,
 'made': 53,
 'though': 54,
 'hate': 55,
 'well': 56,
 'got': 57,
 'happi': 58,
 'thought': 59,
 'someon': 60,
 'didnt': 61,
 'never': 62,
 'felt': 63,
 'find': 64,
 'write': 65,
 'lot': 66,
 'hope': 67,
 'quit': 68,
 'live': 69,
 'week': 70,
 'everi': 71,
 'sure': 72,
 'less': 73,
 'read': 74,
 'enough': 75,
 'give':

In [186]:
tokenizer.document_count

20000

In [187]:
sequences = tokenizer.texts_to_sequences(clean_Data)

In [188]:
sequences= pad_sequences(sequences, maxlen=35, padding='post')

In [189]:
sequences.shape

(20000, 35)

In [190]:
sequences[0:5]

array([[   4,    2,  123,  625,    4, 3696,   41,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   4, 1451,  108,    2,  387,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [  62,    9, 1269,   92,   11,    2,    3,  333,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [  85, 6002,  822, 3184, 4452,  600,    2,  269,  547,  976,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   2,   13,  472,   

In [191]:
unique_labels = pd.Series(np.array(y)).unique()

In [192]:
unique_labels

array(['sadness', 'joy', 'fear', 'anger', 'love', 'surprise'],
      dtype=object)

In [193]:
len(unique_labels)

6

In [194]:
labels_dict = {
    'sadness': 0,
    'love':1,
    'anger':2,
    'surprise':3,
    'fear': 4,
    'joy':5
}

In [195]:
def label_encoder(labels):
    label = []
    for x in labels:
        label.append(labels_dict[x])
    label = np.array(label)
    return label

In [196]:
label = label_encoder(labels=y)

In [197]:
label[0:5]

array([0, 0, 0, 5, 0])

In [198]:
sequences.shape

(20000, 35)

In [199]:
label.shape

(20000,)

In [200]:
x_train, x_test, y_train, y_test = train_test_split(sequences, label,test_size=0.2, random_state=42)

In [201]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((16000, 35), (4000, 35), (16000,), (4000,))

In [213]:
model = Sequential()

In [214]:
no_of_classes = 6  # Unique labels has 6 elements in  output

In [215]:
sequences.shape

(20000, 35)

In [216]:
model.add(SimpleRNN(32, input_shape=(35,1)))  # sequence has 35 number of columns so 35, 1 is in
model.add(Dense(no_of_classes, activation='softmax'))


# Compile model
model.compile(loss = 'sparse_categorical_crossentropy', 
              optimizer='adam', metrics= ['accuracy'])
model.summary()

c:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\rnn\rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_6 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 6)              │           198 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,286 (5.02 KB)

 Trainable params: 1,286 (5.02 KB)

 Non-trainable params: 0 (0.00 B)

In [217]:
x_train.shape, y_train.shape

((16000, 35), (16000,))

In [218]:
model.fit(x_train,y_train, epochs =10, batch_size=32)

Epoch 1/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.3048 - loss: 1.6380
Epoch 2/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.3251 - loss: 1.5800
Epoch 3/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.3354 - loss: 1.5681
Epoch 4/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.3272 - loss: 1.5772
Epoch 5/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.3343 - loss: 1.5778
Epoch 6/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.3328 - loss: 1.5741
Epoch 7/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.3318 - loss: 1.5752
Epoch 8/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.3346 - loss: 1.5746
Epoch 9/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.3326 - loss: 1.5739
Epoch 10/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.3329 - loss: 1.5730


In [219]:
sequences.shape

(20000, 35)

In [220]:
pred = model.predict(np.expand_dims(sequences[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step


In [221]:
pred

array([[0.30442706, 0.08786923, 0.12898028, 0.03830828, 0.11997638,
        0.32043874]], dtype=float32)

In [222]:
unique_labels[np.argmax(pred)]   # argmax function returns index of largest element of given array

'surprise'

In [223]:
pred1 = model.predict(np.expand_dims(sequences[5], axis=1))

2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 57ms/step 


In [224]:
unique_labels[np.argmax(pred1)]

'fear'